### ISSUE TITLE
Xiaomi Query

### ISSUE THREAD

**Issue by kellydarren** [jared-jensen/MiThings#20]
Hey Jared

Just wondering how you got with your Lights?

http://www.aliexpress.com/item/Original-Xiaomi-Mi-Yeelight-LED-Bulb-Colour-Version-Mi-Light-Smartphone-App-WIFI-Control-Light-Eyecare/32662970848.html

And of course I've got to ask, did you buy the Cube in the end ? :-)

**Comment by jared-jensen** [comment]
I did get the cube, and I did get the lights. Lights are really, really nice. I purchased a Raspberry Pi and did some integration work with HomeAssistant last night for them.

Looks like the current future setup may look like:

SmartThings - for compatible Z-Wave/Zigbee devices
HomeAssistant - becomes new "interface", talks/receives from SmartThings, and adds support for
Yeelight bulbs

Not sure. The folks over at MiLight have released v3.0 of their app on the stores, which means the hardware release for the new hub should be anytime now.

**Comment by kellydarren** [comment]
Had to search for HomeAssistant - wow, look like its going to connect with
anything that has opened its api's

well if you have the ability to leverage the yeelight bulbs your well and
truly sorted.

What are you expecting the new hub to be able to provide that the old one
doesn't?

**Comment by jared-jensen** [comment]
The new MiLight hub controls the new lights, which are really nice (and cheap!)
